### ISSUE TITLE
Crash with version 1.1.0-1.17.0

### ISSUE THREAD

**Issue by Zano1999** [andersblomqvist/forge-sulfur-potassium-mod#8]
It crash with fabric 1.17
Below i attach the log file of the crash:

https://pastebin.com/AjnZcVcY

**Comment by andersblomqvist** [comment]
This log file does not give any information on how Sulfur & Potassium mod caused a crash. 
Please look over other mods you have installed which might have caused the crash.

**Comment by Zano1999** [comment]
I've already done it before making this ticket,
With your mod crash, without no

**Comment by andersblomqvist** [comment]
If you could send me your mods folder I can try look at it myself. You should be able to zip the mods folder and drag and drop it here.

**Comment by Zano1999** [comment]
It don't let me upload the zip file, so i create a dropbox link with the list of the mods:

https://www.dropbox.com/s/cs0s285d61np2z9/mods.zip?dl=0

**Comment by andersblomqvist** [comment]
Thanks for the mods. The issue has now been fixed. It was caused by a bad filename which meant that the log did not say anything about what was actually wrong.

* Here is the new download file for the updated mod .jar file: [link to CurseForge](https://www.curseforge.com/minecraft/mc-mods/sulfur-and-potassium-make-more-gunpowder/files/3361985)
